fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      tag: "4.13.1"
    mkdir:
      repo: "https://github.com/flypenguin/puppet-mkdir.git"
      tag: "1.0.4"
    staging:
      repo: "https://github.com/voxpupuli/puppet-staging.git"
      tag: "2.0.1"
    supervisord:
      repo: "https://github.com/ajcrowe/puppet-supervisord.git"
      tag: "0.6.1"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      tag: "2.2.0"

  symlinks:
    talend_job_server: "#{source_dir}"
